# Generated by Django 6.0.4 on 2026-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_attendance_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='used_lessons',
        ),
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
