# Generated by Django 6.0.4 on 2026-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
