# Generated by Django 6.0.4 on 2026-04-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.group'),
        ),
    ]
